The Blog App: Processing Data in Models
romans-adi/IdeaChronicler pull request #2
Opened 2023-08-15 23:30 UTC by romans-adi

This pull request introduces significant enhancements to the project, primarily centered around establishing **associations between models**, implementing **counter updates,** and incorporating **callbacks** for maintaining data integrity. The changes are outlined below:

-  Defined associations between models based on the project's requirements. Associations were established using `belongs_to` and `has_many` directives.
- Added counter attributes to relevant models to keep track of related records, such as the number of `comments`, `likes`, or `posts` for a specific `user` or `post`.
- Implemented counter updates using callback methods triggered after `creating` or `destroying` associated records.
- Introduced `after_create` and `before_destroy` callbacks to update counter attributes.
- Created callback methods to increment or decrement counters for associated records based on the addition or removal of related records.

This PR also includes necessary schema updates, migrations, and any additional changes to support the newly introduced features.

2023-08-15 23:55 UTC, Felix45 requested changes
Hi @romans-adi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] All migrations work as expected :white_check_mark: 
- [x] Most Application models are set up correctly :white_check_mark:  
- [x] Application largely works as expected :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:    


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-15 23:55 UTC, Felix45 commented on app/models/post.rb
> +    user.increment!(:posts_counter)
- [ Required ] I noticed that on this line you are referring to a variable `user` which is not defined in your `Post` model, I think the variable that you should be referring to is `author` which is defined on line `2`. I would like to suggest that you refactor this method as shown below to fix the `Rollback` that occurs when creating a new post for a user.

## Example code
```ruby
  def update_user_posts_counter
    author.increment!(:posts_counter)
  end
```

## Error when creating a post
![Screenshot from 2023-08-16 02-42-31](https://github.com/romans-adi/IdeaChronicler/assets/16392046/9ab402e1-edda-4c9a-8e33-f9fb93424f5d)

2023-08-15 23:55 UTC, Felix45 commented on app/models/post.rb
> +  end
- [ Required ] I noticed that on this line you are referring to a variable `user` which is not defined in your `Post` model, I think the variable that you should be referring to is `author` which is defined on line `2`. I would like to suggest that you refactor this method as shown below to fix the `Rollback` that occurs when creating a new post for a user.

## Example code
```ruby
    def update_user_posts_counter_before_destroy
      author.decrement!(:posts_counter)
    end
```

2023-08-16 00:07 UTC, romans-adi commented on app/models/post.rb
> +    user.increment!(:posts_counter)
Thanks for your feedback, @Felix45 , and I'm sorry for the typo. You're absolutely right. I followed a logical sequence while creating it, but I forgot it's called different. :face_exhaling:

2023-08-16 01:20 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @romans-adi 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following Requirements
✔️ Great work on adding the decrement method 👍

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval. Still, we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 01:20 UTC, HAMMAS-SALEEM commented on app/models/post.rb
>  end
**[OPTIONAL BUT HIGHLY RECOMMENDED]**

- [ ] It would be nice if you put the necessary icons of each heading in the readme file because I can see that all the icons for each heading are missing 😨 Kindly add those missing icons to make your readme attractive and professional 👍

2023-08-16 01:29 UTC, romans-adi commented on app/models/post.rb
>  end
Thank you, @HAMMAS-SALEEM . I wholeheartedly agree that icons contribute to an improved visual aesthetic and facilitate quick identification. Will do that as soon as possible :clap:

2023-08-16 01:31 UTC, closed without merging